name = "ttb"
version = "1.2.1"
license = "MIT"
author = "Andreas Dutzler"
maintainer = "@"
copyright = "Copyright 2024, Andreas Dutzler"
[build]
   auto-executables = true
   auto-tests = true
   auto-examples = true
   module-naming = false
[install]
   library = false
   test = false
[fortran]
   implicit-typing = false
   implicit-external = false
   source-form = "free"

