title: Tensor Toolbox
description: Tensor Toolbox for Modern Fortran
theme: just-the-docs

url: https://adtzlr.github.io/ttb
logo: "assets/images/logo.png"

math: mathjax

callouts:
  warning:
    title: Warning
    color: red
  important:
    title: Important
    color: blue
  note:
    title: Note
    color: purple
  seealso:
    title: See Also
    color: green

last_edit_timestamp: true # requires `last_modified_date` in frontmatter
last_edit_time_format: "%Y-%m-%d"

aux_links:
  Tensor Toolbox on GitHub: https://github.com/adtzlr/ttb
